name: Cypress tests

on:
  pull_request:
    branches:
      - master

jobs:
  cypress-check-web:
    name: Cypress check Web
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
      # options: --user 1001
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - name: Setup Env Variables
        run: |
          mv ./packages/web-ts/.env-wonka ./packages/web-ts/.env
      - name: Install Web Project
        run: yarn install
      - run: chown -R 1001:1001 /github/home/.cache
      - name: Cypress run
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          start: yarn web-ts start-cypress
          config-file: cypress.config.js
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "cypress:server:args"
